function vel=slipvel(m,mu0,r,chi,rd,vis)
%SLIPVEL Calculate the slip velocity of particle
%
%Input: (row vector arrays (1,n))
%	m(3)	-- dipole moment of the permenant magnet
%	r(3)	-- relative location of the field point
%	chi	-- susceptibility of the ferro-particle
%	rd	-- radius of the ferro-particle
%	vis	-- viscosity of the liquid
%	mu0	-- permeability of vacuum
%Output:
%	vel(3)	-- slip (relative) velocity between particle and fluid
%
%Working:
%	H0(3)	-- magnetic field generated by dipole m
%	dH(3,3)	-- grad H0
%	vol	-- particle volume
%
%Record of revisions:
%	03/27/2009, Pengtao Yue, original code
%==================================
%
%mu0=4e-7*pi;
H0=dipoleH(m,r);
dH=graddipH(m,r);
vol=4/3*pi*rd^3;
vel=(mu0*vol/(6*pi*rd*vis))*(3*chi/(3+chi))*(H0*dH);
